# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Doowload Stone Of Orthanc Distribution
      run: |
        mkdir stone
        cd stone
        wget https://lsb.orthanc-server.com/stone-webviewer/2.0/wasm-binaries.zip
        unzip wasm-binaries.zip -d .
        rm wasm-binaries.zip
      working-directory: /tmp
    - name: copy Temporary stone of Orthanc Build to Distribution
      run : mv /tmp/stone/wasm-binaries/StoneWebViewer/* ./src/viewer-stone
    - name: build OHIF Distribution
      run: |
        mkdir ohif
        cd ohif
        git clone https://github.com/OHIF/Viewers.git
        cd Viewers
        yarn install
        QUICK_BUILD=true PUBLIC_URL=/moodle/mod/dicomviewer/viewer-ohif/ yarn run build
      working-directory: /tmp
    - name: copy Temporary OHIF build to Distribution
      run : mv /tmp/ohif/Viewers/platform/viewer/dist/* ./src/viewer-ohif
    - name: OHIF Replace configuration and app-config file
      run : mv ./src/config-ohif/* ./src/viewer-ohif
    - name: STONE Replace configuration file
      run : mv ./src/config-stone/* ./src/viewer-stone
    - uses: actions/upload-artifact@v1
      with:
        name: dicomviewer
        path: ./src/

